obstacle_detector:
  ros__parameters:
    input_topic: "/ZOE3/os_node/points_downsampled_cutoff"
    obstacles_topic: "/obstacles"
    clusters_topic: "/obstacle_clusters"
    max_cluster_publish: 5
    frame_id: "ZOE3/os_sensor"
    ransac_distance_threshold: 0.1 # how far a point can be from the plane to be cosidered part of the plane
    cluster_tolerance: 0.30 # Cluster tolerance in meters (maximum distance between points in a cluster)
    min_cluster_size: 2
    max_cluster_size: 90 # Maximum size of point group to consider as a cluster
    max_cluster_size_select: 90 # Maximum size of cluster to select after intensty ranking 
    max_cluster_publish: 100000
    intensity_threshold: 300.0 # Intensity threshold for filtering points
    max_cluster_size_meters: 1.6
    max_cluster_z_height: -0.5 # Maximum z coordinate height of the cluster in meters
    inflation_radius: 2.5 # How much to "inflate" each point in map cells (e.g. 1 = 3x3 square, 2 = 5x5 square)
    clear_map_interval: 1 # How often to clear the map (after how many calls to the callback)

    max_match_dist: 1.5 
    max_missed_frames: 50
    min_age_frames: 8

    width: 2000        # 150 cells in width
    height: 2000       # 150 cells in height
    resolution: 0.25   # 0.5 m per cell
    offset_x: 700.0
    offset_y: 400.0
